# Generated by Django 5.2.6 on 2025-09-07 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('baju', 'Baju'), ('celana', 'Celana'), ('topi', 'Topi'), ('sepatu', 'Sepatu'), ('update', 'Update')], default='update', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_wanted', models.BooleanField(default=False)),
                ('wishlists', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
