# Generated by Django 5.2.6 on 2025-09-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
