# Generated by Django 5.2.6 on 2025-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='terjual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
